python: can't open file 'api.py': [Errno 2] No such file or directory
[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ENOENT
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35msyscall[0m open
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mpath[0m /root/DigitalTwinCyberrange/package.json
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m -2
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35menoent[0m ENOENT: no such file or directory, open '/root/DigitalTwinCyberrange/package.json'
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35menoent[0m This is related to npm not being able to find a file.
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35menoent[0m 
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.npm/_logs/2021-11-03T15_53_07_333Z-debug.log
[0m